version: "2.2"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ./nginx/localhost.key:/etc/ssl/private/localhost.key:ro
    ports:
      - 80:80
      - 443:443

  auth-server:
    build: auth-server
    command: ["--base-path", "/users/"]

  whoami:
    image: jwilder/whoami
    ports:
      - 8000:8000
